# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GisProject
                                 A QGIS plugin
 This plugin can open shape file (only point geometry), displaying the name of existing layers, change layer visibility, delete duplicate layers, calculate the distance between two selected points using different methods.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-12
        copyright            : (C) 2022 by Cansu Ayten
        email                : cansuayten1@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GisProject class from file GisProject.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gis_project import GisProject
    return GisProject(iface)
